INSERT INTO PUBLIC.USER_ACCOUNT (USERNAME, DISPLAY_NAME, EMAIL) VALUES ('raido', 'Raido', 'raido@example.com');
INSERT INTO PUBLIC.USER_ACCOUNT (USERNAME, DISPLAY_NAME, EMAIL) VALUES ('bob', 'Bob', 'bob@example.com');
INSERT INTO PUBLIC.USER_ACCOUNT (USERNAME, DISPLAY_NAME, EMAIL) VALUES ('alice', 'Alice', 'alice@example.com');

INSERT INTO PUBLIC.MOVIE (TITLE, RELEASE_YEAR, RUNTIME_MINUTES, CREATED_AT) VALUES ('The Matrix', 1999, 136, CURRENT_TIMESTAMP);
INSERT INTO PUBLIC.MOVIE (TITLE, RELEASE_YEAR, RUNTIME_MINUTES, CREATED_AT) VALUES ('Inception', 2010, 148, CURRENT_TIMESTAMP);
INSERT INTO PUBLIC.MOVIE (TITLE, RELEASE_YEAR, RUNTIME_MINUTES, CREATED_AT) VALUES ('Interstellar', 2014, 169, CURRENT_TIMESTAMP);
INSERT INTO PUBLIC.MOVIE (TITLE, RELEASE_YEAR, RUNTIME_MINUTES, CREATED_AT) VALUES ('The Godfather', 1972, 175, CURRENT_TIMESTAMP);

INSERT INTO PUBLIC.USER_MOVIE (USER_ID, MOVIE_ID, STATUS, RATING, COMMENT, WATCHED_AT, CREATED_AT) VALUES (1, 1, 'WATCHED', 10, 'Favorite movie!', '2024-12-01', CURRENT_TIMESTAMP);
INSERT INTO PUBLIC.USER_MOVIE (USER_ID, MOVIE_ID, STATUS, RATING, COMMENT, WATCHED_AT, CREATED_AT) VALUES (1, 2, 'TO_WATCH', NULL, NULL, NULL, CURRENT_TIMESTAMP);
INSERT INTO PUBLIC.USER_MOVIE (USER_ID, MOVIE_ID, STATUS, RATING, COMMENT, WATCHED_AT, CREATED_AT) VALUES (2, 3, 'WATCHED', 9, 'Great sci-fi.', '2025-01-15', CURRENT_TIMESTAMP);
INSERT INTO PUBLIC.USER_MOVIE (USER_ID, MOVIE_ID, STATUS, RATING, COMMENT, WATCHED_AT, CREATED_AT) VALUES (3, 4, 'WATCHED', 8, 'Classic mafia drama.', '2025-02-01', CURRENT_TIMESTAMP);
